[project]
name = "imo-ops"
version = "0.1.0"
description = "imo-ops Data Plateform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.121.2",
    "psycopg2>=2.9.11",
    "pymongo>=4.15.4",
    "scipy>=1.16.3",
    "uvicorn>=0.38.0",
]
