services:
  c4_create_db:
    build: .
    container_name: imo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-imo_db}
      AIRFLOW_USER: ${AIRFLOW_USER}
      AIRFLOW_PASSWORD:  ${AIRFLOW_PASSWORD}
      AIRFLOW_DB: ${AIRFLOW_DB}
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - databox_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-imo_db}"]
      interval: 10s
      retries: 5
      start_period: 10s
#    restart: always
