services:
  c4_create_db:
    build: .
    container_name: imo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-imo_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      imo-ops-network:
        driver: bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-imo_db}"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  imo-ops-network:
    driver: bridge